### ISSUE TITLE
"Map Pin: The War Within"-option unwanted interaction with Map Pin Enhanced

### ISSUE THREAD

**Issue by Eviloverlord1989** [Peterodox/Plumber#17]
Plumber will put icons for Bountiful Delves and Special Assignments on the World Map, it seems by using the BlizzardUI map pins.

When using Plumber in combination with [Map Pin Enhanced](https://www.curseforge.com/wow/addons/mappinenhanced), on every reload, these will be tracked as map pins. Since MPE allows unlimited map pins, it will save and track all of them.

Toggling the option off and on during a session does not reactivate the map pins.

Is it possible to actually clear the map pins for every delve/assignment marked?

**Comment by Peterodox** [comment]
Hi!
Its dev has reached out to me. Updating Plumber to the latest version should fix it.

**Comment by Eviloverlord1989** [comment]
Sorry, I think it's still happening the very first time you get the Special Assignment on your map? But no longer every time you relog/reload.

**Comment by Peterodox** [comment]
Hi! It should have been fixed in v1.6.4.

**Comment by Peterodox** [comment]
I've removed anything that can automatically set waypoints, and our pins only appear on Khaz Algar continent map.
I just downloaded Map Pin Enhanced and encountered no issue. Perhaps check your Map Pin Enhanced settings?

**Comment by Peterodox** [comment]
I'm glad to know it works, otherwise I'm gonna start questioning myself :)
